version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/exodus/
permissions:
  - object: /home/ec2-user/exodus/
    owner: ec2-user
    group: ec2-user
hooks:
  # BeforeInstall:
  #   - location: scripts/build.sh
  #     runas: ec2-user
  BeforeInstall:
    - location: scripts/cleanup.sh
      runas: ec2-user
  # ApplicationStop:
  #   - location: scripts/stop.sh
  #     runas: ec2-user
  ApplicationStart:
    - location: scripts/deploy.sh
      runas: ec2-user
