version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/calculator

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:

  # ApplicationStop:
  #   - location: scripts/stop.sh
  #     runas: ec2-user
  ApplicationStart:
    - location: scripts/deploy.sh
      runas: ec2-user
