
# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - ls -a
      - chmod +x scripts/build.sh
      - chmod +x scripts/pre_build.sh
      - chmod +x scripts/deploy.sh
      - scripts/pre_build.sh
  build:
    commands:
      - echo Build started on `date`
      - scripts/build.sh
  post_build:
    commands:
      - echo Build completed on `date`
