name: CI - Run Tests on Beta

on:
  schedule:
    - cron:  '0 */12 * * *' #run every twelve hours

jobs:
  setup-and-run-ui-tests:
    name: Run UI Tests - Chrome - Beta
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          fetch-depth: 0
          # ref: beta
      - name: Start Server
        run: |
          cd ./backend
          npm ci 
          export SESSION_TOKEN=${{ secrets.SESSION_TOKEN }}
          export AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          export AWS_REGION=${{ secrets.AWS_REGION }}
          npx tsc && node out/src/app.js &

      - name: UI Tests - Chrome
        uses: cypress-io/github-action@v2
        with:
          config: 'baseUrl=http://localhost:5000'
          env: 'username="${{ secrets.TEST_USERNAME }}",password=${{ secrets.TEST_USER_PASSWORD }},xtoken=${{ secrets.TEST_USER_XTOKEN }},apiUrl=http://localhost:8080,CIWait=true'
          start: npm run frontend:start
          wait-on: 'http://localhost:5000, http://localhost:8080/'
          command-prefix: 'percy exec -- npx'
          wait-on-timeout: 120
          browser: chrome
          headless: true
          working-directory: tests
          group: 'UI - Chrome - Beta'
          record: true
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}