name: CI
on:
  push:
    branches: 
      - 'main'
jobs:
  update-server:
    name: Update the Server
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        shell: bash
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/main.key
          chmod 600 ~/.ssh/main.key
          cat >>~/.ssh/config <<END
          Host main
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/main.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SERVER_USERNAME }}
          SSH_KEY: ${{ secrets.SERVER_KEY }}
          SSH_HOST: ${{ secrets.SERVER_HOST }}

      - name: Restart Forever Server
        shell: bash
        run: ssh main 'cd exodus/backend && git fetch && git checkout main && git pull && npm ci && npm run build && sudo forever stopall && sudo forever start out/app.js'
     


  # cypress-test:
  #   name: Run Cypress Tests
  #   needs: update-server
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Run tests on Chrome
  #       uses: cypress-io/github-action@v2
  #       with:
  #         browser: chrome
  #         headless: true
  #         working-directory: e2e
          # group: 'Web browser tests'
        #   record: true
        # env:
        #   CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}


  update-frontend:
    name: Update Front End
    # needs: cypress-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ls
      - run: cd /frontend
      - run: git fetch && git checkout main && git pull
      - run: npm ci
      - run: npm run build
      - run: npm run deploy

      # - name: Deploy
      #   run: ssh main 'cd exodus/frontend && git fetch && git checkout main && git checkout package-lock.json && git pull && npm i && npm run build && npm run deploy'


  

