name: CI
on:
  push:
    branches: 
      - 'test-ci'
jobs:
  # start-server:
  #   name: Start Server
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: |
  #         cd ./backend
  #         git fetch
  #         git checkout test-ci
  #         git pull
  #         npm ci
  #         sudo npm run start
  #     - run: |
  #         cd ./frontend
  #         git fetch
  #         git checkout test-ci 
  #         git pull
  #         npm ci
  #         npm run dev

  servers-up:
    name: Waaaait
    runs-on: ubuntu-latest
    # needs: start-frontend
    steps:
      - uses: actions/checkout@v2
      - run: |
          cd ./backend
          git fetch
          git checkout test-ci
          git pull
          npm ci
          sudo npm run start &
      - run: |
          cd ./frontend
          git fetch
          git checkout test-ci 
          git pull
          npm ci
          npm run dev &
      - name: wait for localhost up
        uses: cypress-io/github-action@v2
        with:
          runTests: false
          working-directory: e2e
          wait-on: 'http://127.0.0.1:5000, http://127.0.0.1:80'
          wait-on-timeout: 180

  cypress-test:
      name: Run Cypress Tests
      runs-on: ubuntu-latest
      needs: servers-up
      steps:
        - uses: actions/checkout@v2
        - name: Run tests on Chrome
          uses: cypress-io/github-action@v2
          with:
            browser: chrome
            install: false
            headless: true
            working-directory: e2e
            # group: 'Web browser tests'
            # record: true
            config: 'baseUrl=http://localhost:5000'
          # env:
          #   CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

  # deploy:
  #   name: deploy
  #   needs: cypress-test
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: cd ./frontend
  #     - run: git fetch && git checkout test-ci && git pull
  #     - run: npm ci
  #     - run: npm run build
  #     - run: npm run deploy

  #     #   run: ssh test-ci 'cd exodus/frontend && git fetch && git checkout test-ci && git checkout package-lock.json && git pull && npm i && npm run build && npm run deploy'

  # update-server:
  #   name: Update the Server
  #   runs-on: ubuntu-latest
  #   needs: cypress-test
  #   steps:
  #     - name: Configure SSH
  #       shell: bash
  #       run: |
  #         mkdir -p ~/.ssh/
  #         echo "$SSH_KEY" > ~/.ssh/test-ci.key
  #         chmod 600 ~/.ssh/test-ci.key
  #         cat >>~/.ssh/config <<END
  #         Host test-ci
  #           HostName $SSH_HOST
  #           User $SSH_USER
  #           IdentityFile ~/.ssh/test-ci.key
  #           StrictHostKeyChecking no
  #         END
  #       env:
  #         SSH_USER: ${{ secrets.SERVER_USERNAME }}
  #         SSH_KEY: ${{ secrets.SERVER_KEY }}
  #         SSH_HOST: ${{ secrets.SERVER_HOST }}

  #     - name: Restart Forever Server
  #       shell: bash
  #       run: ssh test-ci 'cd exodus/backend && git fetch && git checkout test-ci && git pull && npm ci && npm run build && sudo forever stopall && sudo forever start out/app.js'