name: CI
on:
  push:
    branches: 
      - 'main'
jobs:
  cypress-test:
    name: Run Cypress tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests on Chrome
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
        #   record: true
        # env:
        #   CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  update-server:
    name: Update Server
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: cypress-test
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat >>~/.ssh/config <<END
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SERVER_USERNAME }}
          SSH_KEY: ${{ secrets.SERVER_KEY }}
          SSH_HOST: ${{ secrets.SERVER_HOST }}

      - name: Restart the server
        run: ssh staging 'cd exodus/backend && git fetch && git pull && npm i && npm run build && forever restartall'


