name: run tests and update server
on:
  push:
    branches: 
      - 'main'
jobs:
  cypress-test:
    name: Run Cypress tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests on Chrome
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  update-server:
    name: Update Server
    runs-on: ubuntu-latest
    needs: cypress-test
    steps:
      - name: Restart Server
        uses: appleboy/ssh-action@master
        with:
          script: |
            cd exodus/backend
            git pull
            npm i 
            npm run build
            sudo forever restartall
          key: ${{ secrets.EC2_CERT }}
          host: ${{ secrets.EC2_ENDPOINT }}
          username: ubuntu
          port: 22
       
