name: tests
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches: [main, test-coverage]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      # https://github.com/cypress-io/github-action
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          record: true
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        run: cypress run --record --key $CYPRESS_RECORD_KEY 
